config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'movies/index'
  get 'movie/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/index'

  resources :movies do 
    collection do
      get :search
    end
  end 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :pretty_date, :pretty_time
#   before_action :configure_permitted_parameters, if: :devise_controller?
  
  def pretty_date(time = nil)
    time.methods.include?(:strftime) ? time.strftime('%Y-%m-%d') : ''
  end

  def pretty_time(time = nil)
    time.methods.include?(:strftime) ? time.strftime('%Y-%m-%d %H:%M') : ''
  end

#   def configure_permitted_parameters
    # devise_parameter_sanitizer.permit :sign_up, keys: User::USER_COLUMNS
    # devise_parameter_sanitizer.permit :account_update, keys: User::USER_COLUMNS
#   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index 
        @movies = Movie.all
    end 
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def show 
  end

  def search
    @result = Movie.ransack(movie_name_or_movie_content_or_movie_type_cont: params[:q]).result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/index.html.erb
<style>
  .container {
    background-color: white;
    max-width: 1240px !important;
  }
  .pagination .page.current {
    background-color: transparent !important;
    color: rgb(7, 3, 130) !important;
    padding: 0 8px 0 8px !important;
  }
  .banner{
    overflow: hidden;
    background-size: 100% 100% !important;
    background-repeat: no-repeat;
    width: 100%;
    max-height: 350px;
  }
</style>

<div class='container my-4'>
  <form class="pt-3" method="get" action="movies/search">
    <div class="input-group mb-3">
      <input type="text" class="form-control" placeholder="검색" aria-label="search" aria-describedby="button-addon2" name="q">
      <div class="input-group-append">
        <button class="btn btn-outline-primary" type="submit" id="button-addon2">검색</button>
      </div>
    </div>
  </form>
  <p></p>
  <div class="row justify-content-between font-weight-bold mt-5 px-4">
    <h4>영화목록</h4>
    <div><%= @movies.count %>개</div>
  </div>
  <hr class="mt-1 mb-3 color-gray"/>
  <div class="row justify-content-space-around">
    <% @movies.each do |movie| %>
      <%= render movie %>
    <% end %>
  </div>
  <div class="pagination justify-content-center mt-3">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SUPLEX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <style>
      body {
        /* background-color: rgb(242, 242, 242); */
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
      }
      .color-primary {
        color: rgb(7, 3, 130) !important;
      }
      .btn-primary {
        color: #fff !important;
        background-color: rgb(7, 3, 130) !important;
        border-color: rgb(7, 3, 130) !important;
        min-height: 40px !important;
      }
      .btn-primary:hover {
        color: #fff !important;
        background-color: rgb(7, 3, 130) !important;
        border-color: rgb(7, 3, 130) !important;
      }
      .btn-primary:focus, .btn-primary.focus {
        box-shadow: 0 0 0 2px rgb(7, 3, 130) !important;
      }
      .container {
        max-width: 1240px !important;
      }
      .text-gray {
        color: gray;
      }
      .alert-container {
        margin: 0 auto;
        max-width: 1100px;
      }
      .alert-notification {
        position: fixed;
        width:inherit;
        max-width:inherit;
        z-index: 1000;
        padding: 0.75rem 1.25rem;
        margin-top: 0.3rem;
        opacity: 0.9;
        margin-bottom: 1rem;
        border: 1px solid transparent;
        border-radius: 3px;
      }
      .fs-14 {
        font-size: 14px;
      }
    </style>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container alert-container">
      <% if notice %>
        <div class="alert alert-notification alert-success">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-notification alert-danger">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        </div>
      <% end %>
    </div>
    
    <%= yield %>

    <script type="text/javascript">
      <% if notice.present? || alert.present? %>
        $(function() {
          $(".alert-notification").fadeTo(3000, 0.9).slideUp(500, function(){
            $(".alert-notification").alert('close');
          })
        })
      <% end %>
    </script>
  </body>
</html>

app/views/movies/_movie.html.erb
<style>
  .movie-card {
    border: none;
    margin-bottom: 20px;
  }
  .movie-card-img {
    width: 100%;
    height: 100%;
    max-height: 200px;
    background-size: cover;
    background-position: center;
    background-repeat: no-\repeat;
  }
  img {
    background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)) !important;
  }
  .image-gradient{
    position:relative;
    display:inline-block;
  }
  .image-gradient:after {
    content:'';
    position:absolute;
    left:0; top:0;
    width:100%; height:100%;
    display:inline-block;
    background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3))
  }
</style>

<div class="col-md-4 mb-3 px-3">
  <div class="card movie-card">
    <div class="image-gradient">
      <% image_url = movie.image.present? ? movie.image.url : "/image/movie_thumbnail.jpg" %>
      <img class="movie-card-img card-img-top" src="<%= image_url %>">
    </div>
    <div class="card-body px-2">
      <%= link_to movie_path(movie), class: "text-dark" do %>
        <h5 class="font-weight-bold"><%= movie.movie_name %></h5>
      <% end %>
      <p class="card-text"><%= simple_format movie.movie_content.truncate(120) %></p>
      <div class="row justify-content-between small text-muted mt-2 px-3">
        <div class="color-primary"><%= movie.movie_type %></div>
        <div class="color-gray"><%= pretty_date movie.created_at %></div>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

app/views/movies/search.html.erb
<style>
  .container {
    max-width: 1240px !important;
  }
  .pagination .page.current {
    background-color: transparent !important;
    color: rgb(7, 3, 130) !important;
    padding: 0 8px 0 8px !important;
  }
  .banner{
    overflow: hidden;
    background-size: 100% 100% !important;
    background-repeat: no-repeat;
    width: 100%;
    max-height: 450px;
  }
  
</style>

<div class='container my-4'>
  <div class="row justify-content-space-around">
    <% @result.each do |movie| %>
        <%= render movie %>
    <% end %>
  </div>
  <div class="pagination justify-content-center mt-3">
  </div>
</div>

app/views/movies/show.html.erb
영화 내용

app/views/shared/_header.html.erb
<style>
  .font-nav {
    color: rgb(206, 206, 206) !important;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light pl-4 py-3" style="background-color: black !important;">
  <a class="navbar-brand font-weight-bold font-nav" href="/">SUPLEX</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active mr-3">
        <a class="nav-link font-nav" href="/">홈 <span class="sr-only">(current)</span></a>
      </li>
      <% if current_user %>
        <li class="nav-item dropdown mr-3">
          <a class="nav-link dropdown-toggle font-nav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            영화 목록
          </a>
        </li>
        <li class="nav-item mr-3">
          <div class="nav-link font-nav"><%= current_user.email %>님</div>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "nav-link font-nav" %>
        </li>
      <% else %>
        <li class="nav-item mr-3">
          <%= link_to "로그인", new_user_session_path, class: "nav-link font-nav" %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "회원가입", new_user_registration_path, class: "nav-link font-nav" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>